#!/usr/bin/env bash

# Name of the private key
KEY_NAME="school"

# Number of bits in the key
KEY_BITS=4096

# Passphrase to protect the key
KEY_PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $KEY_PASSPHRASE

